chore(deps): allow required plugins in composer
cdn77/RabbitMQBundle pull request #33
Opened 2024-02-02 14:31 UTC by trearcul

2024-02-02 16:51 UTC, baci266 approved these changes

2024-02-04 19:54 UTC, simPod requested changes
a nezapomen shepherd v Readme

2024-02-04 19:54 UTC, simPod commented on composer.json
>          "roave/infection-static-analysis-plugin": "^1.8",
klidne zapal i tohle

2024-02-04 19:54 UTC, simPod commented on infection-psalm.xml.dist
>      </projectFiles>
vsechno psalm related bych vyhodil

2024-02-04 19:54 UTC, simPod commented on .github/workflows/infection.yaml
> +        run: vendor/bin/roave-infection-static-analysis-plugin --threads=$(nproc) --psalm-config=infection-psalm.xml.dist
```suggestion
        run: vendor/bin/infection --threads=$(nproc)
```

uz me ten psalm nebavi :D

2024-02-06 07:39 UTC, simPod approved these changes

2024-02-06 07:39 UTC, simPod commented on composer.json
> +        "sort-packages": true,
dal bych po allow-plugins

2024-02-06 09:52 UTC, merged